import { Price } from "../Price";
import { UserSimple } from "../user/UserSimple";

export type Note = {
  id: number;
  type: string;
  status: string;
  name: string;
  description: string | null;
  price: number;
  key: string;
  slug: string;
  publish_at: string;
  thumbnail_external_url: string;
  eyecatch: string;
  user: UserSimple;
  can_read: boolean;
  is_author: boolean;
  external_url: string | null;
  custom_domain: string | null;
  body: string;
  separator: string;
  is_limited: boolean;
  is_trial: boolean;
  can_update: boolean;
  tweet_text: string;
  is_refund: boolean;
  highlight: string;
  eyecatch_type_2: string | null;
  sp_eyecatch: string;
  category: string | null;
  comment_count: number;
  like_count: number;
  is_liked: boolean;
  is_included_private_purchase_magazine: boolean;
  image_count: number;
  format: string;
  audio: Record<string, any>;
  is_membership_connected: boolean;
  has_available_circle_plans: boolean;
  discount_campaigns: any[];
  pictures: any[];
  price_info: Price;
};
