export type User = {
  id: number;
  key: string;
  nickname: string;
  urlname: string;
  profile: string;
  noteCount: number;
  magazineCount: number;
  followingCount: number;
  followerCount: number;
  isFollowing: boolean;
  isFollowed: boolean;
  isMyself: boolean;
  originalHeaderImageUrl: string;
  headerImageUrl: string;
  headerImageKey: string;
  profileImageUrl: string;
  profileImageKey: string;
  isBlocked: boolean;
  blocksYou: boolean;
  isAdmin: boolean;
  socials: {
    twitter?: {
      id: number;
      nickname: string;
      name: string;
      uid: string;
    };
  };
  isOfficial: boolean;
  showFollowCount: boolean;
  externalLinks: Record<string, unknown>;
  disableSupport: boolean;
  hasStore: boolean;
  hasCircle: boolean;
  customDomain: string | null;
  followAppealText: string;
  followAppealImage: string;
  isCreatorLikesTabEnabled: boolean;
  isCreatorMagazinesTabEnabled: boolean;
  isCreatorCirclesTabEnabled: boolean;
  isCreatorArchivesTabEnabled: boolean;
  isCreatorProfileTabEnabled: boolean;
  isCreatorJobOfferTabEnabled: boolean;
  isCreatorFollowNumberDisplayed: boolean;
  isCreatorPopularSortEnabled: boolean;
  style: string;
  isPro: boolean;
  proUserId: number | null;
  tlMagazines: unknown[];
  isMedia: boolean;
  storeUrl: string;
  jobSourceUrl: string | null;
  isHavingSubscribableMagazines: boolean;
};
